class AppStrings {
  const AppStrings({
    required this.locale,
    // Bottom Nav
    required this.navHome,
    required this.navPractice,
    required this.navMockExam,
    required this.navSettings,
    // Common
    required this.confirm,
    required this.cancel,
    required this.save,
    required this.delete,
    required this.edit,
    required this.close,
    required this.back,
    required this.next,
    required this.prev,
    required this.search,
    required this.all,
    required this.retry,
    required this.loading,
    required this.error,
    required this.completed,
    required this.bookmark,
    required this.bookmarked,
    required this.listenPronunciation,
    required this.round,
    // Home Page
    required this.homeTitle,
    required this.homeGreeting,
    required this.homeSubtitle,
    required this.examSchedule,
    required this.noUpcomingExam,
    required this.daysLeft,
    required this.quickStudy,
    required this.quickStudyDesc,
    required this.bookmarksSummary,
    required this.bookmarksSummaryDesc,
    required this.questionsCount,
    required this.vocabCount,
    required this.grammarCount,
    required this.mockExamBannerTitle,
    required this.mockExamBannerDesc,
    required this.startMockExam,
    // Practice Page
    required this.practiceTitle,
    required this.practiceHeroTitle,
    required this.practiceHeroSubtitle,
    required this.byTypeSection,
    required this.readingPractice,
    required this.readingPracticeDesc,
    required this.listeningPractice,
    required this.listeningPracticeDesc,
    required this.writingPractice,
    required this.writingPracticeDesc,
    required this.studyToolsSection,
    required this.smartWordbook,
    required this.smartWordbookDesc,
    required this.grammarStudy,
    required this.grammarStudyDesc,
    // Vocabulary Hub & OneVoca
    required this.oneVocaTitle,
    required this.oneVocaSubtitle,
    required this.flashcard,
    required this.flashcardDesc,
    required this.quiz,
    required this.quizDesc,
    required this.dictation,
    required this.dictationDesc,
    required this.autoplay,
    required this.autoplayDesc,
    required this.savedWords,
    required this.addToVocabulary,
    required this.savedToVocabulary,
    required this.searchVocabulary,
    required this.flipCardHint,
    required this.memorized,
    required this.needReview,
    required this.submitAnswer,
    required this.correctAnswer,
    required this.wrongAnswer,
    required this.studySourceSheetTitle,
    required this.mySavedWordbook,
    required this.mySavedWordbookDesc,
    required this.allTopikVocab,
    required this.allTopikVocabDesc,
    required this.wordsSavedCount,
    // Grammar Hub
    required this.searchGrammarHint,
    required this.examples,
    required this.grammarDetail,
    required this.addToGrammar,
    required this.savedToGrammar,
    // Home New Features
    required this.dailyWordChallenge,
    required this.dailyWordChallengeDesc,
    required this.startOneVoca,
    required this.todayGrammar,
    required this.todayGrammarDesc,
    required this.dailyStreak,
    required this.streakDays,
    required this.quickPractice,
    required this.targetLevelLabel,
    required this.wordsCount,
    // Grammar New Features (OneGrammar)
    required this.oneGrammarTitle,
    required this.oneGrammarSubtitle,
    required this.grammarFlashcard,
    required this.grammarFlashcardDesc,
    required this.grammarQuiz,
    required this.grammarQuizDesc,
    required this.grammarUsage,
    required this.grammarCategoryAll,
    required this.grammarCategoryReason,
    required this.grammarCategoryContrast,
    required this.grammarCategoryPurpose,
    required this.grammarCategoryCondition,
    required this.grammarCategoryTime,
    required this.grammarCategoryOther,
    required this.quizScoreResult,
    required this.nextQuestion,
    required this.retryQuiz,
    required this.finishStudy,
    required this.noGrammarForQuiz,
    // Word Lookup Sheet
    required this.dictTitle,
    required this.searchWordOrGrammar,
    required this.vocabSection,
    required this.grammarSection,
    required this.dictNoResultsDesc,
    required this.dictTranslationLabel,
    required this.dictTranslating,
    required this.viewNaverDict,
    // Mock Exam
    required this.mockExamTitle,
    required this.selectExamSession,
    required this.startExam,
    required this.remainingTime,
    required this.submitExam,
    required this.confirmSubmitExam,
    required this.examResult,
    required this.totalScore,
    required this.viewExplanation,
    // Practice Controls
    required this.questionNumberLabel,
    required this.dictionary,
    required this.viewScript,
    required this.charCount,
    required this.modelAnswer,
    // Bookmarks Page
    required this.bookmarkedQuestions,
    required this.bookmarkedVocab,
    required this.bookmarkedGrammar,
    required this.noBookmarks,
    // Settings Page
    required this.settingsTitle,
    required this.appSettingsHeroTitle,
    required this.appSettingsHeroDesc,
    required this.generalSettings,
    required this.username,
    required this.email,
    required this.role,
    required this.languageSetting,
    required this.chooseLanguage,
    required this.languageChangedNotice,
    required this.targetLevel,
    required this.fontSize,
    required this.timezone,
    required this.dataManagement,
    required this.clearBookmarks,
    required this.clearBookmarksDesc,
    required this.appInfo,
    required this.appInfoDesc,
    required this.accountSection,
    required this.changePassword,
    required this.logout,
    required this.adminMenu,
    required this.manageUsers,
    required this.manageQuestionSets,
  });

  final String locale;

  // Bottom Nav
  final String navHome;
  final String navPractice;
  final String navMockExam;
  final String navSettings;

  // Common
  final String confirm;
  final String cancel;
  final String save;
  final String delete;
  final String edit;
  final String close;
  final String back;
  final String next;
  final String prev;
  final String search;
  final String all;
  final String retry;
  final String loading;
  final String error;
  final String completed;
  final String bookmark;
  final String bookmarked;
  final String listenPronunciation;
  final String round;

  // Home Page
  final String homeTitle;
  final String homeGreeting;
  final String homeSubtitle;
  final String examSchedule;
  final String noUpcomingExam;
  final String daysLeft;
  final String quickStudy;
  final String quickStudyDesc;
  final String bookmarksSummary;
  final String bookmarksSummaryDesc;
  final String questionsCount;
  final String vocabCount;
  final String grammarCount;
  final String mockExamBannerTitle;
  final String mockExamBannerDesc;
  final String startMockExam;

  // Practice Page
  final String practiceTitle;
  final String practiceHeroTitle;
  final String practiceHeroSubtitle;
  final String byTypeSection;
  final String readingPractice;
  final String readingPracticeDesc;
  final String listeningPractice;
  final String listeningPracticeDesc;
  final String writingPractice;
  final String writingPracticeDesc;
  final String studyToolsSection;
  final String smartWordbook;
  final String smartWordbookDesc;
  final String grammarStudy;
  final String grammarStudyDesc;

  // Vocabulary Hub & OneVoca
  final String oneVocaTitle;
  final String oneVocaSubtitle;
  final String flashcard;
  final String flashcardDesc;
  final String quiz;
  final String quizDesc;
  final String dictation;
  final String dictationDesc;
  final String autoplay;
  final String autoplayDesc;
  final String savedWords;
  final String addToVocabulary;
  final String savedToVocabulary;
  final String searchVocabulary;
  final String flipCardHint;
  final String memorized;
  final String needReview;
  final String submitAnswer;
  final String correctAnswer;
  final String wrongAnswer;
  final String studySourceSheetTitle;
  final String mySavedWordbook;
  final String mySavedWordbookDesc;
  final String allTopikVocab;
  final String allTopikVocabDesc;
  final String wordsSavedCount;

  // Grammar Hub
  final String searchGrammarHint;
  final String examples;
  final String grammarDetail;
  final String addToGrammar;
  final String savedToGrammar;
  // Home New Features
  final String dailyWordChallenge;
  final String dailyWordChallengeDesc;
  final String startOneVoca;
  final String todayGrammar;
  final String todayGrammarDesc;
  final String dailyStreak;
  final String streakDays;
  final String quickPractice;
  final String targetLevelLabel;
  final String wordsCount;
  // Grammar New Features (OneGrammar)
  final String oneGrammarTitle;
  final String oneGrammarSubtitle;
  final String grammarFlashcard;
  final String grammarFlashcardDesc;
  final String grammarQuiz;
  final String grammarQuizDesc;
  final String grammarUsage;
  final String grammarCategoryAll;
  final String grammarCategoryReason;
  final String grammarCategoryContrast;
  final String grammarCategoryPurpose;
  final String grammarCategoryCondition;
  final String grammarCategoryTime;
  final String grammarCategoryOther;
  final String quizScoreResult;
  final String nextQuestion;
  final String retryQuiz;
  final String finishStudy;
  final String noGrammarForQuiz;

  // Word Lookup Sheet
  final String dictTitle;
  final String searchWordOrGrammar;
  final String vocabSection;
  final String grammarSection;
  final String dictNoResultsDesc;
  final String dictTranslationLabel;
  final String dictTranslating;
  final String viewNaverDict;

  // Mock Exam
  final String mockExamTitle;
  final String selectExamSession;
  final String startExam;
  final String remainingTime;
  final String submitExam;
  final String confirmSubmitExam;
  final String examResult;
  final String totalScore;
  final String viewExplanation;

  // Practice Controls
  final String questionNumberLabel;
  final String dictionary;
  final String viewScript;
  final String charCount;
  final String modelAnswer;

  // Bookmarks Page
  final String bookmarkedQuestions;
  final String bookmarkedVocab;
  final String bookmarkedGrammar;
  final String noBookmarks;

  // Settings Page
  final String settingsTitle;
  final String appSettingsHeroTitle;
  final String appSettingsHeroDesc;
  final String generalSettings;
  final String username;
  final String email;
  final String role;
  final String languageSetting;
  final String chooseLanguage;
  final String languageChangedNotice;
  final String targetLevel;
  final String fontSize;
  final String timezone;
  final String dataManagement;
  final String clearBookmarks;
  final String clearBookmarksDesc;
  final String appInfo;
  final String appInfoDesc;
  final String accountSection;
  final String changePassword;
  final String logout;
  final String adminMenu;
  final String manageUsers;
  final String manageQuestionSets;

  static AppStrings of(String? code) {
    switch (code) {
      case 'en':
        return _en;
      case 'uz':
        return _uz;
      case 'ru':
        return _ru;
      case 'vi':
        return _vi;
      case 'zh':
        return _zh;
      case 'ja':
        return _ja;
      case 'fr':
        return _fr;
      case 'de':
        return _de;
      case 'ko':
      default:
        return _ko;
    }
  }

  // -------------------------------------------------------------
  // Korean (한국어 - 기본)
  // -------------------------------------------------------------
  static const AppStrings _ko = AppStrings(
    locale: 'ko',
    navHome: '홈',
    navPractice: '학습',
    navMockExam: '모의고사',
    navSettings: '설정',
    confirm: '확인',
    cancel: '취소',
    save: '저장',
    delete: '삭제',
    edit: '수정',
    close: '닫기',
    back: '뒤로',
    next: '다음',
    prev: '이전',
    search: '검색',
    all: '전체',
    retry: '다시 시도',
    loading: '불러오는 중...',
    error: '오류가 발생했습니다',
    completed: '완료',
    bookmark: '북마크',
    bookmarked: '저장됨',
    listenPronunciation: '발음 듣기',
    round: '회차',
    homeTitle: '홈',
    homeGreeting: '안녕하세요, {name}님!',
    homeSubtitle: '오늘도 목표 등급을 향해 함께 달려봐요.',
    examSchedule: '시험 일정',
    noUpcomingExam: '예정된 시험 일정이 없습니다.',
    daysLeft: 'D-{days}',
    quickStudy: '학습 바로가기',
    quickStudyDesc: '매일 꾸준한 연습으로 실력을 쌓아보세요.',
    bookmarksSummary: '북마크',
    bookmarksSummaryDesc: '다시 보고 싶은 자료를 모아두는 공간입니다.',
    questionsCount: '문제 {count}개',
    vocabCount: '단어 {count}개',
    grammarCount: '문법 {count}개',
    mockExamBannerTitle: '실전 모의고사',
    mockExamBannerDesc: '실전 시험처럼 풀어보고 점수를 확인하세요.',
    startMockExam: '모의고사 시작',
    practiceTitle: '학습',
    practiceHeroTitle: '학습',
    practiceHeroSubtitle: '영역별 집중 훈련과 학습 도구로 효율적인 TOPIK 대비를 시작하세요.',
    byTypeSection: '유형별 문제 풀기',
    readingPractice: 'TOPIK II 읽기 연습',
    readingPracticeDesc: 'TOPIK II 기출 읽기 (제102회 · 제83회 전 문항 수록)',
    listeningPractice: 'TOPIK II 듣기 연습',
    listeningPracticeDesc: 'TOPIK II 기출 듣기 (실제 성우 음원 & 전 문항 대본)',
    writingPractice: 'TOPIK II 쓰기 집중 훈련',
    writingPracticeDesc: 'TOPIK II 기출 쓰기 (51~54번 원고지 실전 & 모범 답안)',
    studyToolsSection: '학습 도구',
    smartWordbook: '스마트 단어장',
    smartWordbookDesc: '원보카 4대 암기 (플래시카드 · 퀴즈 · 받아쓰기 · 자동재생)',
    grammarStudy: '문법 공부',
    grammarStudyDesc: 'TOPIK 필수 문법 패턴 검색 및 예문 확인',
    oneVocaTitle: '원보카 4대 암기 모드',
    oneVocaSubtitle: '플래시카드 · 퀴즈 · 받아쓰기 · 자동재생으로 완벽 암기',
    flashcard: '플래시카드',
    flashcardDesc: '넘기면서 단어 뜻 확인',
    quiz: '객관식 퀴즈',
    quizDesc: '4지선다형 맞춤 테스트',
    dictation: '받아쓰기',
    dictationDesc: '초성 힌트로 스펠링 훈련',
    autoplay: '자동재생',
    autoplayDesc: '이동 중 귀로 듣는 단어장',
    savedWords: '★ 내 저장 단어',
    addToVocabulary: '+ 내 단어장에 추가',
    savedToVocabulary: '단어장에 저장됨',
    searchVocabulary: '단어 검색',
    flipCardHint: '카드를 탭하여 뜻 확인',
    memorized: '외웠어요',
    needReview: '다시 볼래요',
    submitAnswer: '정답 제출',
    correctAnswer: '정답입니다!',
    wrongAnswer: '아쉬워요! 정답: ',
    studySourceSheetTitle: '학습할 단어 선택',
    mySavedWordbook: '내 저장 단어장',
    mySavedWordbookDesc: '문제 풀이 중 지문에서 저장한 맞춤 단어 집중 학습',
    allTopikVocab: '전체 TOPIK 필수 어휘',
    allTopikVocabDesc: 'TOPIK 시험에 자주 출제되는 필수 어휘 전체 학습',
    wordsSavedCount: '{count}개 저장됨',
    searchGrammarHint: '문법 검색 (예: -는데, -기 때문에)',
    examples: '예문',
    grammarDetail: '문법 상세',
    addToGrammar: '+ 내 문법장에 추가',
    savedToGrammar: '문법장에 저장됨',
    dailyWordChallenge: '오늘의 단어 챌린지',
    dailyWordChallengeDesc: '매일 10개 단어로 TOPIK 어휘 완성하기',
    startOneVoca: '원보카 4대 모드로 학습하기',
    todayGrammar: '오늘의 문법',
    todayGrammarDesc: '하루 1문법으로 문장 구조 마스터',
    dailyStreak: '연속 학습',
    streakDays: '{days}일 연속',
    quickPractice: '실전 연습 바로가기',
    targetLevelLabel: '목표',
    wordsCount: '{count}개 단어',
    oneGrammarTitle: '원그래머 문법 학습',
    oneGrammarSubtitle: '플래시카드 · 빈칸 퀴즈로 TOPIK 문법 완벽 정복',
    grammarFlashcard: '문법 플래시카드',
    grammarFlashcardDesc: '패턴 · 결합 규칙 · 예문 넘겨보기',
    grammarQuiz: '문법 빈칸 퀴즈',
    grammarQuizDesc: '예문 빈칸에 알맞은 문법 고르기 (실전형)',
    grammarUsage: '결합 규칙',
    grammarCategoryAll: '전체',
    grammarCategoryReason: '이유·원인',
    grammarCategoryContrast: '대조·양보',
    grammarCategoryPurpose: '목적·의도',
    grammarCategoryCondition: '조건·가정',
    grammarCategoryTime: '시간·순서',
    grammarCategoryOther: '기타',
    quizScoreResult: '{total}문제 중 {correct}문제 정답!',
    nextQuestion: '다음 문제',
    retryQuiz: '다시 풀기',
    finishStudy: '학습 완료',
    noGrammarForQuiz: '학습할 문법 데이터가 부족합니다.',
    dictTitle: '단어 · 문법 사전',
    searchWordOrGrammar: '단어 또는 문법 검색...',
    vocabSection: '어휘 (단어)',
    grammarSection: '문법 표현',
    dictNoResultsDesc: '사전 기본 등록어 목록에 없지만,\n내 단어장에 바로 추가하여 나중에 복습할 수 있습니다.',
    dictTranslationLabel: '번역: ',
    dictTranslating: '번역 불러오는 중...',
    viewNaverDict: '네이버 국어사전에서 자세히 보기',
    mockExamTitle: '모의고사',
    selectExamSession: '시험 회차 선택',
    startExam: '시험 시작하기',
    remainingTime: '남은 시간',
    submitExam: '시험 제출',
    confirmSubmitExam: '시험을 제출하시겠습니까?',
    examResult: '시험 결과',
    totalScore: '총점',
    viewExplanation: '해설 보기',
    questionNumberLabel: '{number}번 문제',
    dictionary: '사전',
    viewScript: '대본 보기',
    charCount: '글자 수',
    modelAnswer: '모범 답안',
    bookmarkedQuestions: '저장된 문제',
    bookmarkedVocab: '내 단어장',
    bookmarkedGrammar: '내 문법장',
    noBookmarks: '저장된 항목이 없습니다.',
    settingsTitle: '설정',
    appSettingsHeroTitle: '앱 설정',
    appSettingsHeroDesc: '계정, 학습 환경, 언어 설정을 한 곳에서 관리하세요.',
    generalSettings: '일반 설정',
    username: '사용자명',
    email: '이메일',
    role: '역할',
    languageSetting: '언어 설정',
    chooseLanguage: '언어 선택 (Language)',
    languageChangedNotice: '언어가 변경되었습니다.',
    targetLevel: '목표 등급',
    fontSize: '글자 크기',
    timezone: '타임존',
    dataManagement: '데이터 관리',
    clearBookmarks: '북마크 초기화',
    clearBookmarksDesc: '저장된 모든 북마크 삭제',
    appInfo: '앱 정보',
    appInfoDesc: '버전 정보 및 각종 정책 안내',
    accountSection: '계정',
    changePassword: '비밀번호 변경',
    logout: '로그아웃',
    adminMenu: '관리자 메뉴',
    manageUsers: '사용자 관리',
    manageQuestionSets: '문제 세트 관리',
  );

  // -------------------------------------------------------------
  // English
  // -------------------------------------------------------------
  static const AppStrings _en = AppStrings(
    locale: 'en',
    navHome: 'Home',
    navPractice: 'Practice',
    navMockExam: 'Mock Exam',
    navSettings: 'Settings',
    confirm: 'Confirm',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    prev: 'Previous',
    search: 'Search',
    all: 'All',
    retry: 'Retry',
    loading: 'Loading...',
    error: 'An error occurred',
    completed: 'Completed',
    bookmark: 'Bookmark',
    bookmarked: 'Saved',
    listenPronunciation: 'Pronounce',
    round: 'Round',
    homeTitle: 'Home',
    homeGreeting: 'Hello, {name}!',
    homeSubtitle: "Let's reach your target TOPIK level together.",
    examSchedule: 'Exam Schedule',
    noUpcomingExam: 'No upcoming exam scheduled.',
    daysLeft: '{days} days left',
    quickStudy: 'Quick Study',
    quickStudyDesc: 'Build your skills with daily steady practice.',
    bookmarksSummary: 'Bookmarks',
    bookmarksSummaryDesc: 'Your saved questions, words, and grammar.',
    questionsCount: '{count} Questions',
    vocabCount: '{count} Words',
    grammarCount: '{count} Grammar',
    mockExamBannerTitle: 'Real Mock Exam',
    mockExamBannerDesc: 'Practice with authentic timed exam conditions.',
    startMockExam: 'Start Mock Exam',
    practiceTitle: 'Practice',
    practiceHeroTitle: 'Practice',
    practiceHeroSubtitle: 'Effective TOPIK preparation with targeted training and smart tools.',
    byTypeSection: 'Practice by Section',
    readingPractice: 'Reading Practice',
    readingPracticeDesc: 'TOPIK II Reading (Full questions from 102nd & 83rd)',
    listeningPractice: 'Listening Practice',
    listeningPracticeDesc: 'TOPIK II Listening (Voice actor audio & full scripts)',
    writingPractice: 'Writing Practice',
    writingPracticeDesc: 'TOPIK II Writing (Q51~54 Manuscript sheet & model answers)',
    studyToolsSection: 'Study Tools',
    smartWordbook: 'Smart Wordbook',
    smartWordbookDesc: 'OneVoca 4 Modes (Flashcards, Quiz, Dictation, Autoplay)',
    grammarStudy: 'Grammar Study',
    grammarStudyDesc: 'Search essential TOPIK grammar patterns & examples',
    oneVocaTitle: 'OneVoca 4 Memorization Modes',
    oneVocaSubtitle: 'Master words with Flashcards, Quiz, Dictation, and Autoplay',
    flashcard: 'Flashcards',
    flashcardDesc: 'Flip cards and check meanings',
    quiz: 'Multiple-Choice Quiz',
    quizDesc: '4-choice customized test',
    dictation: 'Dictation',
    dictationDesc: 'Spelling training with consonant hints',
    autoplay: 'Autoplay',
    autoplayDesc: 'Hands-free vocabulary audio player',
    savedWords: '★ Saved Words',
    addToVocabulary: '+ Add to My Vocabulary',
    savedToVocabulary: 'Saved in Vocabulary',
    searchVocabulary: 'Search vocabulary',
    flipCardHint: 'Tap card to flip',
    memorized: 'Memorized',
    needReview: 'Review Again',
    submitAnswer: 'Submit',
    correctAnswer: 'Correct!',
    wrongAnswer: 'Incorrect! Correct answer: ',
    studySourceSheetTitle: 'Select Words to Study',
    mySavedWordbook: 'My Saved Vocabulary',
    mySavedWordbookDesc: 'Focus on words saved while solving practice passages',
    allTopikVocab: 'All TOPIK Essential Vocabulary',
    allTopikVocabDesc: 'Comprehensive study of high-frequency TOPIK vocabulary',
    wordsSavedCount: '{count} Saved',
    searchGrammarHint: 'Search grammar (e.g. -는데, -기 때문에)',
    examples: 'Examples',
    grammarDetail: 'Grammar Details',
    addToGrammar: '+ Add to My Grammar',
    savedToGrammar: 'Saved in Grammar',
    dailyWordChallenge: 'Daily Word Challenge',
    dailyWordChallengeDesc: 'Master TOPIK vocabulary with 10 words daily',
    startOneVoca: 'Study with OneVoca 4 Modes',
    todayGrammar: "Today's Grammar",
    todayGrammarDesc: 'Master sentence structures with 1 grammar daily',
    dailyStreak: 'Daily Streak',
    streakDays: '{days} days streak',
    quickPractice: 'Quick Practice',
    targetLevelLabel: 'Target',
    wordsCount: '{count} words',
    oneGrammarTitle: 'OneGrammar Study Modes',
    oneGrammarSubtitle: 'Master TOPIK grammar with Flashcards & Cloze Quizzes',
    grammarFlashcard: 'Grammar Flashcards',
    grammarFlashcardDesc: 'Flip patterns, conjugation rules & examples',
    grammarQuiz: 'Grammar Cloze Quiz',
    grammarQuizDesc: 'Fill in blanks with correct grammar (TOPIK style)',
    grammarUsage: 'Conjugation Rules',
    grammarCategoryAll: 'All',
    grammarCategoryReason: 'Reason & Cause',
    grammarCategoryContrast: 'Contrast & Concession',
    grammarCategoryPurpose: 'Purpose & Intention',
    grammarCategoryCondition: 'Condition & Hypothesis',
    grammarCategoryTime: 'Time & Sequence',
    grammarCategoryOther: 'Other',
    quizScoreResult: '{correct} / {total} Correct!',
    nextQuestion: 'Next Question',
    retryQuiz: 'Retry Quiz',
    finishStudy: 'Finish',
    noGrammarForQuiz: 'Not enough grammar items for quiz.',
    dictTitle: 'Word & Grammar Dictionary',
    searchWordOrGrammar: 'Search word or grammar...',
    vocabSection: 'Vocabulary (Words)',
    grammarSection: 'Grammar Expressions',
    dictNoResultsDesc: 'Not in dictionary catalog, but you can add it to your vocabulary to review later.',
    dictTranslationLabel: 'Translation: ',
    dictTranslating: 'Translating...',
    viewNaverDict: 'View in Naver Korean Dictionary',
    mockExamTitle: 'Mock Exam',
    selectExamSession: 'Select Exam Session',
    startExam: 'Start Exam',
    remainingTime: 'Time Remaining',
    submitExam: 'Submit Exam',
    confirmSubmitExam: 'Are you sure you want to submit the exam?',
    examResult: 'Exam Result',
    totalScore: 'Total Score',
    viewExplanation: 'View Explanations',
    questionNumberLabel: 'Question {number}',
    dictionary: 'Dictionary',
    viewScript: 'View Script',
    charCount: 'Character Count',
    modelAnswer: 'Model Answer',
    bookmarkedQuestions: 'Saved Questions',
    bookmarkedVocab: 'My Vocabulary',
    bookmarkedGrammar: 'My Grammar',
    noBookmarks: 'No saved items yet.',
    settingsTitle: 'Settings',
    appSettingsHeroTitle: 'App Settings',
    appSettingsHeroDesc: 'Manage your account, study preferences, and language in one place.',
    generalSettings: 'General Settings',
    username: 'Username',
    email: 'Email',
    role: 'Role',
    languageSetting: 'Language',
    chooseLanguage: 'Select Language',
    languageChangedNotice: 'Language updated.',
    targetLevel: 'Target Level',
    fontSize: 'Font Size',
    timezone: 'Timezone',
    dataManagement: 'Data Management',
    clearBookmarks: 'Reset Bookmarks',
    clearBookmarksDesc: 'Delete all saved bookmarks',
    appInfo: 'App Info',
    appInfoDesc: 'Version info & terms of service',
    accountSection: 'Account',
    changePassword: 'Change Password',
    logout: 'Log Out',
    adminMenu: 'Admin Menu',
    manageUsers: 'Manage Users',
    manageQuestionSets: 'Manage Question Sets',
  );

  // -------------------------------------------------------------
  // Uzbek (O'zbekcha)
  // -------------------------------------------------------------
  static const AppStrings _uz = AppStrings(
    locale: 'uz',
    navHome: 'Bosh sahifa',
    navPractice: "O'rganish",
    navMockExam: 'Sinov imtihoni',
    navSettings: 'Sozlamalar',
    confirm: 'Tasdiqlash',
    cancel: 'Bekor qilish',
    save: 'Saqlash',
    delete: "O'chirish",
    edit: 'Tahrirlash',
    close: 'Yopish',
    back: 'Orqaga',
    next: 'Keyingi',
    prev: 'Oldingi',
    search: 'Qidirish',
    all: 'Barchasi',
    retry: 'Qayta urinish',
    loading: 'Yuklanmoqda...',
    error: 'Xatolik yuz berdi',
    completed: 'Bajarildi',
    bookmark: "Xatcho'p",
    bookmarked: 'Saqlandi',
    listenPronunciation: 'Tinglash',
    round: 'Bosqich',
    homeTitle: 'Bosh sahifa',
    homeGreeting: 'Salom, {name}!',
    homeSubtitle: "Bugun ham maqsadli TOPIK darajangiz sari birga intilamiz.",
    examSchedule: 'Imtihon jadvali',
    noUpcomingExam: 'Yaqin orada rejalashtirilgan imtihon yo‘q.',
    daysLeft: '{days} kun qoldi',
    quickStudy: "Tezkor o'rganish",
    quickStudyDesc: "Har kungi doimiy mashqlar bilan darajangizni oshiring.",
    bookmarksSummary: "Xatcho'plar",
    bookmarksSummaryDesc: "Saqlangan savollar, so'zlar va grammatika.",
    questionsCount: '{count} ta savol',
    vocabCount: "{count} ta so'z",
    grammarCount: '{count} ta grammatika',
    mockExamBannerTitle: 'Haqiqiy sinov imtihoni',
    mockExamBannerDesc: "Haqiqiy imtihon sharoitida vaqt bilan ishlab ko'ring.",
    startMockExam: 'Imtihonni boshlash',
    practiceTitle: "O'rganish",
    practiceHeroTitle: "O'rganish",
    practiceHeroSubtitle: "Sohalar bo'yicha mashqlar va aqlli vositalar bilan TOPIKga tayyorlaning.",
    byTypeSection: "Bo'limlar bo'yicha mashq qilish",
    readingPractice: "O'qish mashqi",
    readingPracticeDesc: "TOPIK II O'qish (102 va 83-son barcha savollari)",
    listeningPractice: 'Tinglash mashqi',
    listeningPracticeDesc: "TOPIK II Tinglash (Haqiqiy diktor ovozi va to'liq matn)",
    writingPractice: 'Yozish mashqi',
    writingPracticeDesc: "TOPIK II Yozish (51~54-savol katak varaq va namunaviy javob)",
    studyToolsSection: "O'quv qurollari",
    smartWordbook: "Aqlli lug'at",
    smartWordbookDesc: "OneVoca 4 usuli (Kartochkalar, Test, Diktant, Avto-ijro)",
    grammarStudy: 'Grammatika',
    grammarStudyDesc: "TOPIK asosiy grammatik qoidalari va misollari",
    oneVocaTitle: 'OneVoca 4 ta yodlash usuli',
    oneVocaSubtitle: "Kartochkalar, Test, Diktant va Avto-ijro orqali mukammal yodlang",
    flashcard: 'Flesh-kartalar',
    flashcardDesc: "Kartani aylantirib ma'nosini ko'rish",
    quiz: 'Test viktorina',
    quizDesc: "4 ta variantli moslashuvchan test",
    dictation: 'Imlo mashqi (Diktant)',
    dictationDesc: 'Bosh harf shartlari bilan yozish mashqi',
    autoplay: 'Avtomatik ijro',
    autoplayDesc: "Yo'lda quloqchin orqali so'zlarni tinglash",
    savedWords: "★ Saqlangan so'zlar",
    addToVocabulary: "+ Lug'atga qo'shish",
    savedToVocabulary: "Lug'atga saqlandi",
    searchVocabulary: "So'z qidirish",
    flipCardHint: "Kartani bosing va ma'nosini ko'ring",
    memorized: 'Yodladim',
    needReview: 'Qaytarish kerak',
    submitAnswer: 'Javobni tekshirish',
    correctAnswer: "To'g'ri!",
    wrongAnswer: "Noto'g'ri! To'g'ri javob: ",
    studySourceSheetTitle: "O'rganish uchun so'zlarni tanlang",
    mySavedWordbook: "Mening saqlangan lug'atim",
    mySavedWordbookDesc: "Matnlardan saqlab olingan shaxsiy so'zlar",
    allTopikVocab: "Barcha TOPIK asosiy lug'ati",
    allTopikVocabDesc: "Imtihonda eng ko'p uchraydigan muhim so'zlar to'plami",
    wordsSavedCount: '{count} ta saqlangan',
    searchGrammarHint: 'Grammatika qidirish (masalan: -는데, -기 때문에)',
    examples: 'Misollar',
    grammarDetail: 'Grammatika tafsilotlari',
    addToGrammar: "+ Grammatikaga qo'shish",
    savedToGrammar: 'Grammatikaga saqlandi',
    dailyWordChallenge: 'Kunlik so‘z chaqiruvi',
    dailyWordChallengeDesc: 'Kuniga 10 ta so‘z bilan TOPIK lug‘atini o‘zlashtiring',
    startOneVoca: 'OneVoca 4 ta usulida o‘rganish',
    todayGrammar: 'Bugungi grammatika',
    todayGrammarDesc: 'Kuniga 1 ta grammatika bilan gap tuzishni o‘rganing',
    dailyStreak: 'Davomiylik',
    streakDays: '{days} kun ketma-ket',
    quickPractice: 'Amaliy mashqqa o‘tish',
    targetLevelLabel: 'Maqsad',
    wordsCount: '{count} ta so‘z',
    oneGrammarTitle: 'OneGrammar o‘rganish rejimi',
    oneGrammarSubtitle: 'Fleshkarta va test orqali TOPIK grammatikasini o‘rganing',
    grammarFlashcard: 'Grammatika fleshkartasi',
    grammarFlashcardDesc: 'Shakllar, qoidalar va misollarni varaqlab o‘rganing',
    grammarQuiz: 'Grammatika bo‘shliq testi',
    grammarQuizDesc: 'Bo‘sh joyga mos grammatikani tanlang (TOPIK formati)',
    grammarUsage: 'Qo‘llanish qoidasi',
    grammarCategoryAll: 'Barchasi',
    grammarCategoryReason: 'Sabab va oqibat',
    grammarCategoryContrast: 'Zidlik va taqqoslash',
    grammarCategoryPurpose: 'Maqsad va niyat',
    grammarCategoryCondition: 'Shart va faraz',
    grammarCategoryTime: 'Vaqt va tartib',
    grammarCategoryOther: 'Boshqa',
    quizScoreResult: '{total} tadan {correct} ta to‘g‘ri!',
    nextQuestion: 'Keyingi savol',
    retryQuiz: 'Qayta topshirish',
    finishStudy: 'Tugatish',
    noGrammarForQuiz: 'Test uchun grammatik maʼlumot yetarli emas.',
    dictTitle: "Lug'at va grammatika",
    searchWordOrGrammar: "So'z yoki grammatika qidiring...",
    vocabSection: "Lug'at (So'zlar)",
    grammarSection: 'Grammatik qoidalar',
    dictNoResultsDesc: "Lug'atda topilmadi, ammo uni shaxsiy lug'atingizga saqlab qaytarishingiz mumkin.",
    dictTranslationLabel: 'Tarjima: ',
    dictTranslating: 'Tarjima qilinmoqda...',
    viewNaverDict: "Naver lug'atida batafsil ko'rish",
    mockExamTitle: 'Sinov imtihoni',
    selectExamSession: 'Imtihon sessiyasini tanlang',
    startExam: 'Imtihonni boshlash',
    remainingTime: 'Qolgan vaqt',
    submitExam: 'Imtihonni topshirish',
    confirmSubmitExam: 'Imtihonni yakunlab topshirasizmi?',
    examResult: 'Imtihon natijasi',
    totalScore: 'Umumiy ball',
    viewExplanation: "Tushuntirishlarni ko'rish",
    questionNumberLabel: '{number}-savol',
    dictionary: "Lug'at",
    viewScript: "Matnni ko'rish",
    charCount: 'Belgilar soni',
    modelAnswer: 'Namunaviy javob',
    bookmarkedQuestions: 'Saqlangan savollar',
    bookmarkedVocab: "Mening lug'atim",
    bookmarkedGrammar: 'Mening grammatikam',
    noBookmarks: "Saqlangan ma'lumotlar yo'q.",
    settingsTitle: 'Sozlamalar',
    appSettingsHeroTitle: 'Ilova sozlamalari',
    appSettingsHeroDesc: "Hisobingiz, o'rganish muhiti va til sozlamalarini boshqaring.",
    generalSettings: 'Umumiy sozlamalar',
    username: 'Foydalanuvchi nomi',
    email: 'Elektron pochta',
    role: 'Rol',
    languageSetting: 'Til sozlamasi',
    chooseLanguage: 'Tilni tanlash (Language)',
    languageChangedNotice: "Til muvaffaqiyatli o'zgartirildi.",
    targetLevel: 'Maqsadli daraja',
    fontSize: "Shrift o'lchami",
    timezone: 'Vaqt mintaqasi',
    dataManagement: "Ma'lumotlarni boshqarish",
    clearBookmarks: "Xatcho'plarni tozalash",
    clearBookmarksDesc: "Barcha saqlangan xatcho'plarni o'chirish",
    appInfo: 'Ilova haqida',
    appInfoDesc: "Versiya ma'lumotlari va qoidalar",
    accountSection: 'Akkaunt',
    changePassword: "Parolni o'zgartirish",
    logout: 'Chiqish',
    adminMenu: 'Admin menyusi',
    manageUsers: 'Foydalanuvchilarni boshqarish',
    manageQuestionSets: "Savol to'plamlarini boshqarish",
  );

  // -------------------------------------------------------------
  // Russian (Русский)
  // -------------------------------------------------------------
  static const AppStrings _ru = AppStrings(
    locale: 'ru',
    navHome: 'Главная',
    navPractice: 'Обучение',
    navMockExam: 'Экзамен',
    navSettings: 'Настройки',
    confirm: 'Подтвердить',
    cancel: 'Отмена',
    save: 'Сохранить',
    delete: 'Удалить',
    edit: 'Изменить',
    close: 'Закрыть',
    back: 'Назад',
    next: 'Далее',
    prev: 'Назад',
    search: 'Поиск',
    all: 'Все',
    retry: 'Повторить',
    loading: 'Загрузка...',
    error: 'Произошла ошибка',
    completed: 'Завершено',
    bookmark: 'Закладка',
    bookmarked: 'Сохранено',
    listenPronunciation: 'Озвучить',
    round: 'Сессия',
    homeTitle: 'Главная',
    homeGreeting: 'Здравствуйте, {name}!',
    homeSubtitle: 'Идем к вашей целевой оценке TOPIK каждый день.',
    examSchedule: 'Расписание экзаменов',
    noUpcomingExam: 'Ближайших экзаменов нет.',
    daysLeft: 'Осталось {days} дн.',
    quickStudy: 'Быстрый старт',
    quickStudyDesc: 'Улучшайте навыки с помощью ежедневной практики.',
    bookmarksSummary: 'Закладки',
    bookmarksSummaryDesc: 'Сохраненные вопросы, слова и грамматика.',
    questionsCount: '{count} вопр.',
    vocabCount: '{count} слов',
    grammarCount: '{count} грамм.',
    mockExamBannerTitle: 'Пробный экзамен',
    mockExamBannerDesc: 'Тренируйтесь в условиях реального экзамена с таймером.',
    startMockExam: 'Начать экзамен',
    practiceTitle: 'Обучение',
    practiceHeroTitle: 'Обучение',
    practiceHeroSubtitle: 'Эффективная подготовка к TOPIK с практическими инструментами.',
    byTypeSection: 'Тренировка по разделам',
    readingPractice: 'Чтение (Чтение)',
    readingPracticeDesc: 'TOPIK II Чтение (Все вопросы 102 и 83 сессий)',
    listeningPractice: 'Аудирование (Слушание)',
    listeningPracticeDesc: 'TOPIK II Слушание (Официальное аудио и транскрипция)',
    writingPractice: 'Письмо (Сочинение)',
    writingPracticeDesc: 'TOPIK II Письмо (Задания 51~54, бланк и образцы ответов)',
    studyToolsSection: 'Инструменты обучения',
    smartWordbook: 'Умный словарь',
    smartWordbookDesc: '4 режима OneVoca (Карточки, Тест, Диктант, Авто)',
    grammarStudy: 'Грамматика',
    grammarStudyDesc: 'Поиск грамматических конструкций TOPIK с примерами',
    oneVocaTitle: '4 режима запоминания OneVoca',
    oneVocaSubtitle: 'Учите слова с помощью Карточек, Тестов, Диктантов и Авто-плеера',
    flashcard: 'Карточки',
    flashcardDesc: 'Переворачивайте карточки и проверяйте значения',
    quiz: 'Тест-викторина',
    quizDesc: 'Тест с выбором из 4 вариантов',
    dictation: 'Диктант',
    dictationDesc: 'Тренировка правописания с подсказками',
    autoplay: 'Авто-плеер',
    autoplayDesc: 'Слушайте слова в дороге без рук',
    savedWords: '★ Мои сохраненные',
    addToVocabulary: '+ В мой словарь',
    savedToVocabulary: 'Сохранено в словаре',
    searchVocabulary: 'Поиск слова',
    flipCardHint: 'Нажмите, чтобы перевернуть',
    memorized: 'Выучено',
    needReview: 'Повторить',
    submitAnswer: 'Проверить',
    correctAnswer: 'Правильно!',
    wrongAnswer: 'Неверно! Ответ: ',
    studySourceSheetTitle: 'Выберите слова для изучения',
    mySavedWordbook: 'Мой личный словарь',
    mySavedWordbookDesc: 'Слова, сохраненные во время разбора заданий',
    allTopikVocab: 'Весь базовый словарь TOPIK',
    allTopikVocabDesc: 'Изучение всех частотных слов экзамена',
    wordsSavedCount: 'Сохранено: {count}',
    searchGrammarHint: 'Поиск грамматики (напр. -는데, -기 때문에)',
    examples: 'Примеры',
    grammarDetail: 'Подробнее о грамматике',
    addToGrammar: '+ В список грамматики',
    savedToGrammar: 'Сохранено в грамматике',
    dailyWordChallenge: 'Слово дня: Челлендж',
    dailyWordChallengeDesc: 'Учите по 10 слов в день для экзамена TOPIK',
    startOneVoca: 'Учить в 4 режимах OneVoca',
    todayGrammar: 'Грамматика дня',
    todayGrammarDesc: '1 грамматическая конструкция каждый день',
    dailyStreak: 'Серия дней',
    streakDays: '{days} дн. подряд',
    quickPractice: 'Быстрая тренировка',
    targetLevelLabel: 'Цель',
    wordsCount: '{count} слов',
    oneGrammarTitle: 'Изучение OneGrammar',
    oneGrammarSubtitle: 'Освойте грамматику TOPIK с карточками и тестами',
    grammarFlashcard: 'Карточки грамматики',
    grammarFlashcardDesc: 'Правила присоединения, примеры и значения',
    grammarQuiz: 'Тест на заполнение пропусков',
    grammarQuizDesc: 'Выберите подходящую грамматику для пропуска в примере',
    grammarUsage: 'Правила присоединения',
    grammarCategoryAll: 'Все',
    grammarCategoryReason: 'Причина',
    grammarCategoryContrast: 'Противопоставление',
    grammarCategoryPurpose: 'Цель',
    grammarCategoryCondition: 'Условие',
    grammarCategoryTime: 'Время и порядок',
    grammarCategoryOther: 'Другое',
    quizScoreResult: '{correct} из {total} правильно!',
    nextQuestion: 'Следующий вопрос',
    retryQuiz: 'Пройти снова',
    finishStudy: 'Завершить',
    noGrammarForQuiz: 'Недостаточно данных для теста.',
    dictTitle: 'Словарь и грамматика',
    searchWordOrGrammar: 'Введите слово или грамматику...',
    vocabSection: 'Лексика (Слова)',
    grammarSection: 'Грамматические структуры',
    dictNoResultsDesc: 'В базе словаря нет, но вы можете сохранить его в свой словарь.',
    dictTranslationLabel: 'Перевод: ',
    dictTranslating: 'Переводим...',
    viewNaverDict: 'Открыть в словаре Naver',
    mockExamTitle: 'Пробный экзамен',
    selectExamSession: 'Выберите номер сессии',
    startExam: 'Начать экзамен',
    remainingTime: 'Оставшееся время',
    submitExam: 'Завершить экзамен',
    confirmSubmitExam: 'Вы уверены, что хотите сдать работу?',
    examResult: 'Результат экзамена',
    totalScore: 'Общий балл',
    viewExplanation: 'Смотреть объяснения',
    questionNumberLabel: 'Вопрос №{number}',
    dictionary: 'Словарь',
    viewScript: 'Текст аудио',
    charCount: 'Количество символов',
    modelAnswer: 'Образец ответа',
    bookmarkedQuestions: 'Сохраненные вопросы',
    bookmarkedVocab: 'Мой словарь',
    bookmarkedGrammar: 'Моя грамматика',
    noBookmarks: 'Пока ничего не сохранено.',
    settingsTitle: 'Настройки',
    appSettingsHeroTitle: 'Настройки приложения',
    appSettingsHeroDesc: 'Управляйте профилем, языком интерфейса и параметрами обучения.',
    generalSettings: 'Основные настройки',
    username: 'Имя пользователя',
    email: 'Эл. почта',
    role: 'Роль',
    languageSetting: 'Язык приложения',
    chooseLanguage: 'Выберите язык (Language)',
    languageChangedNotice: 'Язык успешно изменен.',
    targetLevel: 'Целевой уровень',
    fontSize: 'Размер шрифта',
    timezone: 'Часовой пояс',
    dataManagement: 'Управление данными',
    clearBookmarks: 'Очистить закладки',
    clearBookmarksDesc: 'Удалить все сохраненные материалы',
    appInfo: 'О приложении',
    appInfoDesc: 'Версия и правила использования',
    accountSection: 'Аккаунт',
    changePassword: 'Сменить пароль',
    logout: 'Выйти из аккаунта',
    adminMenu: 'Панель администратора',
    manageUsers: 'Пользователи',
    manageQuestionSets: 'Наборы вопросов',
  );

  // -------------------------------------------------------------
  // Vietnamese (Tiếng Việt)
  // -------------------------------------------------------------
  static const AppStrings _vi = AppStrings(
    locale: 'vi',
    navHome: 'Trang chủ',
    navPractice: 'Học tập',
    navMockExam: 'Thi thử',
    navSettings: 'Cài đặt',
    confirm: 'Xác nhận',
    cancel: 'Hủy',
    save: 'Lưu',
    delete: 'Xóa',
    edit: 'Sửa',
    close: 'Đóng',
    back: 'Quay lại',
    next: 'Tiếp theo',
    prev: 'Trước',
    search: 'Tìm kiếm',
    all: 'Tất cả',
    retry: 'Thử lại',
    loading: 'Đang tải...',
    error: 'Đã xảy ra lỗi',
    completed: 'Hoàn thành',
    bookmark: 'Dấu trang',
    bookmarked: 'Đã lưu',
    listenPronunciation: 'Nghe phát âm',
    round: 'Kỳ thi',
    homeTitle: 'Trang chủ',
    homeGreeting: 'Xin chào, {name}!',
    homeSubtitle: 'Cùng nhau chinh phục cấp độ TOPIK mục tiêu nhé.',
    examSchedule: 'Lịch thi',
    noUpcomingExam: 'Không có kỳ thi nào sắp tới.',
    daysLeft: 'Còn {days} ngày',
    quickStudy: 'Học nhanh',
    quickStudyDesc: 'Nâng cao kỹ năng với bài tập luyện đều đặn mỗi ngày.',
    bookmarksSummary: 'Dấu trang',
    bookmarksSummaryDesc: 'Tổng hợp câu hỏi, từ vựng và ngữ pháp đã lưu.',
    questionsCount: '{count} câu hỏi',
    vocabCount: '{count} từ vựng',
    grammarCount: '{count} ngữ pháp',
    mockExamBannerTitle: 'Thi thử thực chiến',
    mockExamBannerDesc: 'Luyện đề như thi thật kèm tính giờ chuẩn xác.',
    startMockExam: 'Bắt đầu thi thử',
    practiceTitle: 'Luyện tập',
    practiceHeroTitle: 'Luyện tập',
    practiceHeroSubtitle: 'Luyện theo từng kỹ năng và công cụ học TOPIK hiệu quả.',
    byTypeSection: 'Luyện theo từng phần',
    readingPractice: 'Luyện Đọc',
    readingPracticeDesc: 'Đọc hiểu TOPIK II (Đầy đủ đề kỳ 102 & 83)',
    listeningPractice: 'Luyện Nghe',
    listeningPracticeDesc: 'Nghe hiểu TOPIK II (Âm thanh chuẩn & phụ đề đầy đủ)',
    writingPractice: 'Luyện Viết',
    writingPracticeDesc: 'Viết TOPIK II (Câu 51~54 giấy kẻ ô & đáp án mẫu)',
    studyToolsSection: 'Công cụ học tập',
    smartWordbook: 'Sổ từ thông minh',
    smartWordbookDesc: '4 chế độ OneVoca (Thẻ từ, Trắc nghiệm, Chính tả, Tự động)',
    grammarStudy: 'Học ngữ pháp',
    grammarStudyDesc: 'Tra cứu mẫu ngữ pháp quan trọng và câu ví dụ',
    oneVocaTitle: '4 chế độ ghi nhớ OneVoca',
    oneVocaSubtitle: 'Thuộc từ vựng qua Thẻ từ, Trắc nghiệm, Chính tả và Tự phát',
    flashcard: 'Thẻ ghi nhớ',
    flashcardDesc: 'Lật thẻ kiểm tra nghĩa của từ',
    quiz: 'Trắc nghiệm',
    quizDesc: 'Kiểm tra 4 lựa chọn',
    dictation: 'Chính tả',
    dictationDesc: 'Luyện gõ chữ với gợi ý phụ âm đầu',
    autoplay: 'Tự động phát',
    autoplayDesc: 'Nghe từ vựng rảnh tay khi di chuyển',
    savedWords: '★ Từ đã lưu',
    addToVocabulary: '+ Thêm vào sổ từ',
    savedToVocabulary: 'Đã lưu vào sổ từ',
    searchVocabulary: 'Tìm từ vựng',
    flipCardHint: 'Chạm để lật thẻ',
    memorized: 'Đã thuộc',
    needReview: 'Cần xem lại',
    submitAnswer: 'Kiểm tra đáp án',
    correctAnswer: 'Chính xác!',
    wrongAnswer: 'Chưa đúng! Đáp án: ',
    studySourceSheetTitle: 'Chọn từ vựng để học',
    mySavedWordbook: 'Sổ từ của tôi',
    mySavedWordbookDesc: 'Học tập trung những từ đã lưu khi làm bài',
    allTopikVocab: 'Toàn bộ từ vựng TOPIK cần thiết',
    allTopikVocabDesc: 'Tổng hợp đầy đủ từ vựng tần suất cao trong đề thi',
    wordsSavedCount: 'Đã lưu {count} từ',
    searchGrammarHint: 'Tìm ngữ pháp (ví dụ: -는데, -기 때문에)',
    examples: 'Ví dụ',
    grammarDetail: 'Chi tiết ngữ pháp',
    addToGrammar: '+ Thêm vào ngữ pháp',
    savedToGrammar: 'Đã lưu vào ngữ pháp',
    dailyWordChallenge: 'Thử thách từ vựng mỗi ngày',
    dailyWordChallengeDesc: 'Học 10 từ mỗi ngày để chinh phục từ vựng TOPIK',
    startOneVoca: 'Học với 4 chế độ OneVoca',
    todayGrammar: 'Ngữ pháp hôm nay',
    todayGrammarDesc: 'Làm chủ cấu trúc câu với 1 ngữ pháp mỗi ngày',
    dailyStreak: 'Chuỗi học tập',
    streakDays: '{days} ngày liên tiếp',
    quickPractice: 'Luyện tập nhanh',
    targetLevelLabel: 'Mục tiêu',
    wordsCount: '{count} từ vựng',
    oneGrammarTitle: 'Chế độ học OneGrammar',
    oneGrammarSubtitle: 'Chinh phục ngữ pháp TOPIK với Flashcard & Trắc nghiệm',
    grammarFlashcard: 'Flashcard ngữ pháp',
    grammarFlashcardDesc: 'Lật thẻ xem quy tắc kết hợp và ví dụ minh họa',
    grammarQuiz: 'Trắc nghiệm điền khuyết',
    grammarQuizDesc: 'Chọn ngữ pháp chính xác điền vào chỗ trống',
    grammarUsage: 'Quy tắc kết hợp',
    grammarCategoryAll: 'Tất cả',
    grammarCategoryReason: 'Lý do & Nguyên nhân',
    grammarCategoryContrast: 'Tương phản & Nhượng bộ',
    grammarCategoryPurpose: 'Mục đích & Dự định',
    grammarCategoryCondition: 'Điều kiện & Giả định',
    grammarCategoryTime: 'Thời gian & Trình tự',
    grammarCategoryOther: 'Khác',
    quizScoreResult: 'Đúng {correct}/{total} câu!',
    nextQuestion: 'Câu tiếp theo',
    retryQuiz: 'Làm lại',
    finishStudy: 'Hoàn thành',
    noGrammarForQuiz: 'Chưa đủ dữ liệu ngữ pháp để làm bài test.',
    dictTitle: 'Từ điển Từ vựng · Ngữ pháp',
    searchWordOrGrammar: 'Tìm kiếm từ hoặc ngữ pháp...',
    vocabSection: 'Từ vựng',
    grammarSection: 'Ngữ pháp',
    dictNoResultsDesc: 'Từ chưa có trong danh mục sẵn, bạn có thể lưu vào sổ từ để ôn lại sau.',
    dictTranslationLabel: 'Bản dịch: ',
    dictTranslating: 'Đang dịch...',
    viewNaverDict: 'Xem chi tiết trên từ điển Naver',
    mockExamTitle: 'Thi thử',
    selectExamSession: 'Chọn kỳ thi',
    startExam: 'Bắt đầu làm bài',
    remainingTime: 'Thời gian còn lại',
    submitExam: 'Nộp bài',
    confirmSubmitExam: 'Bạn có chắc chắn muốn nộp bài thi không?',
    examResult: 'Kết quả bài thi',
    totalScore: 'Tổng điểm',
    viewExplanation: 'Xem giải thích',
    questionNumberLabel: 'Câu hỏi số {number}',
    dictionary: 'Từ điển',
    viewScript: 'Xem kịch bản',
    charCount: 'Số ký tự',
    modelAnswer: 'Bài mẫu tham khảo',
    bookmarkedQuestions: 'Câu hỏi đã lưu',
    bookmarkedVocab: 'Sổ từ của tôi',
    bookmarkedGrammar: 'Ngữ pháp của tôi',
    noBookmarks: 'Chưa có mục nào được lưu.',
    settingsTitle: 'Cài đặt',
    appSettingsHeroTitle: 'Cài đặt ứng dụng',
    appSettingsHeroDesc: 'Quản lý tài khoản, môi trường học tập và ngôn ngữ giao diện.',
    generalSettings: 'Cài đặt chung',
    username: 'Tên người dùng',
    email: 'Email',
    role: 'Vai trò',
    languageSetting: 'Ngôn ngữ',
    chooseLanguage: 'Chọn ngôn ngữ (Language)',
    languageChangedNotice: 'Đã thay đổi ngôn ngữ.',
    targetLevel: 'Mục tiêu cấp độ',
    fontSize: 'Cỡ chữ',
    timezone: 'Múi giờ',
    dataManagement: 'Quản lý dữ liệu',
    clearBookmarks: 'Xóa dấu trang',
    clearBookmarksDesc: 'Xóa tất cả các mục đã lưu',
    appInfo: 'Thông tin ứng dụng',
    appInfoDesc: 'Phiên bản & chính sách',
    accountSection: 'Tài khoản',
    changePassword: 'Đổi mật khẩu',
    logout: 'Đăng xuất',
    adminMenu: 'Menu Quản trị',
    manageUsers: 'Quản lý người dùng',
    manageQuestionSets: 'Quản lý bộ đề',
  );

  // -------------------------------------------------------------
  // Chinese (中文)
  // -------------------------------------------------------------
  static const AppStrings _zh = AppStrings(
    locale: 'zh',
    navHome: '首页',
    navPractice: '学习',
    navMockExam: '模拟考试',
    navSettings: '设置',
    confirm: '确认',
    cancel: '取消',
    save: '保存',
    delete: '删除',
    edit: '编辑',
    close: '关闭',
    back: '返回',
    next: '下一步',
    prev: '上一步',
    search: '搜索',
    all: '全部',
    retry: '重试',
    loading: '加载中...',
    error: '发生错误',
    completed: '完成',
    bookmark: '书签',
    bookmarked: '已保存',
    listenPronunciation: '听发音',
    round: '届次',
    homeTitle: '首页',
    homeGreeting: '你好，{name}！',
    homeSubtitle: '今天也一起朝着目标等级冲刺吧。',
    examSchedule: '考试日程',
    noUpcomingExam: '暂无临近的考试安排。',
    daysLeft: '倒计时 {days} 天',
    quickStudy: '快捷学习',
    quickStudyDesc: '坚持每日练习，扎实提升韩语实力。',
    bookmarksSummary: '我的书签',
    bookmarksSummaryDesc: '收录重点题目、词汇与语法的空间。',
    questionsCount: '{count}道题',
    vocabCount: '{count}个词',
    grammarCount: '{count}条语法',
    mockExamBannerTitle: '实战模拟考试',
    mockExamBannerDesc: '如真实考试般严格计时，测算你的应考得分。',
    startMockExam: '开始模考',
    practiceTitle: '学习',
    practiceHeroTitle: '学习专区',
    practiceHeroSubtitle: '专项突破与智能学习工具，助你高效备考 TOPIK。',
    byTypeSection: '题型专项训练',
    readingPractice: '阅读练习',
    readingPracticeDesc: 'TOPIK II 真题阅读（收录第102届 · 第83届全部试题）',
    listeningPractice: '听力练习',
    listeningPracticeDesc: 'TOPIK II 真题听力（官方原声录音及全套原文）',
    writingPractice: '写作特训',
    writingPracticeDesc: 'TOPIK II 写作训练（51~54题答题原稿纸与范文）',
    studyToolsSection: '学习工具',
    smartWordbook: '智能单词本',
    smartWordbookDesc: 'OneVoca 4大记忆模式（闪卡 · 测验 · 听写 · 自动播放）',
    grammarStudy: '语法学习',
    grammarStudyDesc: '查询必备语法条目并对照实际例句',
    oneVocaTitle: 'OneVoca 4大记忆模式',
    oneVocaSubtitle: '卡片轮播、选择测验、拼写听写与随身朗读全方位攻克词汇',
    flashcard: '单词闪卡',
    flashcardDesc: '翻转卡片高效复习释义',
    quiz: '单项测验',
    quizDesc: '4选1定制化巩固检测',
    dictation: '拼写听写',
    dictationDesc: '借助初声提示强化单词拼写',
    autoplay: '自动轮播',
    autoplayDesc: '通勤路上戴上耳机听单词',
    savedWords: '★ 我的收藏单词',
    addToVocabulary: '+ 加入单词本',
    savedToVocabulary: '已加入单词本',
    searchVocabulary: '搜索单词',
    flipCardHint: '轻触卡片查看释义',
    memorized: '已记住',
    needReview: '稍后复习',
    submitAnswer: '提交答案',
    correctAnswer: '回答正确！',
    wrongAnswer: '回答错误！正确答案：',
    studySourceSheetTitle: '选择要学习的词库',
    mySavedWordbook: '我的收藏词库',
    mySavedWordbookDesc: '重点复习做题过程中收录的专属词汇',
    allTopikVocab: '全量 TOPIK 核心词汇',
    allTopikVocabDesc: '考试常考高频词汇全盘学习',
    wordsSavedCount: '已收录 {count} 个',
    searchGrammarHint: '搜索语法（例如：-는데, -기 때문에）',
    examples: '例句',
    grammarDetail: '语法详情',
    addToGrammar: '+ 加入语法本',
    savedToGrammar: '已加入语法本',
    dailyWordChallenge: '每日单词挑战',
    dailyWordChallengeDesc: '每天10个单词，轻松攻克TOPIK核心词汇',
    startOneVoca: '使用OneVoca四大模式学习',
    todayGrammar: '今日语法',
    todayGrammarDesc: '每天掌握一个核心语法结构',
    dailyStreak: '连续学习',
    streakDays: '连续 {days} 天',
    quickPractice: '快捷实战练习',
    targetLevelLabel: '目标',
    wordsCount: '{count}个单词',
    oneGrammarTitle: 'OneGrammar 语法学习',
    oneGrammarSubtitle: '通过翻转卡片与填空测验攻克TOPIK语法',
    grammarFlashcard: '语法卡片',
    grammarFlashcardDesc: '查看语法接续规则、释义及精选例句',
    grammarQuiz: '语法填空测验',
    grammarQuizDesc: '根据语境选择最符合的语法填入空格（真题形式）',
    grammarUsage: '接续规则',
    grammarCategoryAll: '全部',
    grammarCategoryReason: '原因·理由',
    grammarCategoryContrast: '对照·让步',
    grammarCategoryPurpose: '目的·意图',
    grammarCategoryCondition: '条件·假设',
    grammarCategoryTime: '时间·顺序',
    grammarCategoryOther: '其他',
    quizScoreResult: '答对 {correct} / {total} 题！',
    nextQuestion: '下一题',
    retryQuiz: '重新测验',
    finishStudy: '完成学习',
    noGrammarForQuiz: '语法练习数据不足。',
    dictTitle: '词汇 · 语法小词典',
    searchWordOrGrammar: '输入单词或语法...',
    vocabSection: '词汇',
    grammarSection: '语法表现',
    dictNoResultsDesc: '该词未在系统词库中，但您可以直接收录到单词本以便后续复习。',
    dictTranslationLabel: '翻译：',
    dictTranslating: '正在翻译...',
    viewNaverDict: '在 Naver 韩语词典中查看',
    mockExamTitle: '模拟考试',
    selectExamSession: '选择考试届次',
    startExam: '开始考试',
    remainingTime: '剩余时间',
    submitExam: '交卷',
    confirmSubmitExam: '确认提交模拟考试答卷吗？',
    examResult: '考试成绩',
    totalScore: '总得分',
    viewExplanation: '查看试题解析',
    questionNumberLabel: '第 {number} 题',
    dictionary: '词典',
    viewScript: '查看原文',
    charCount: '字符统计',
    modelAnswer: '参考范文',
    bookmarkedQuestions: '收录题目',
    bookmarkedVocab: '我的单词本',
    bookmarkedGrammar: '我的语法本',
    noBookmarks: '暂无收录内容。',
    settingsTitle: '设置',
    appSettingsHeroTitle: '应用设置',
    appSettingsHeroDesc: '集中管理您的账户信息、学习偏好与界面语言。',
    generalSettings: '通用设置',
    username: '用户名',
    email: '电子邮箱',
    role: '身份角色',
    languageSetting: '界面语言',
    chooseLanguage: '选择语言 (Language)',
    languageChangedNotice: '语言已更新。',
    targetLevel: '目标等级',
    fontSize: '字体大小',
    timezone: '时区',
    dataManagement: '数据管理',
    clearBookmarks: '清空书签',
    clearBookmarksDesc: '删除所有已收藏的内容',
    appInfo: '关于应用',
    appInfoDesc: '版本详情与服务政策',
    accountSection: '账户安全',
    changePassword: '修改密码',
    logout: '退出登录',
    adminMenu: '管理员菜单',
    manageUsers: '用户管理',
    manageQuestionSets: '试卷题库管理',
  );

  // -------------------------------------------------------------
  // Japanese (日本語)
  // -------------------------------------------------------------
  static const AppStrings _ja = AppStrings(
    locale: 'ja',
    navHome: 'ホーム',
    navPractice: '学習',
    navMockExam: '模擬試験',
    navSettings: '設定',
    confirm: '確認',
    cancel: 'キャンセル',
    save: '保存',
    delete: '削除',
    edit: '編集',
    close: '閉じる',
    back: '戻る',
    next: '次へ',
    prev: '前へ',
    search: '検索',
    all: 'すべて',
    retry: '再試行',
    loading: '読み込み中...',
    error: 'エラーが発生しました',
    completed: '完了',
    bookmark: 'ブックマーク',
    bookmarked: '保存済み',
    listenPronunciation: '発音を聞く',
    round: '回次',
    homeTitle: 'ホーム',
    homeGreeting: 'こんにちは、{name}さん！',
    homeSubtitle: '今日も目標級に向けて一緒に頑張りましょう。',
    examSchedule: '試験日程',
    noUpcomingExam: '予定されている試験はありません。',
    daysLeft: '残り{days}日',
    quickStudy: '学習ショートカット',
    quickStudyDesc: '日々の練習で確実にスコアを伸ばしましょう。',
    bookmarksSummary: 'ブックマーク',
    bookmarksSummaryDesc: '保存した問題・単語・文法を見返す場所です。',
    questionsCount: '問題 {count}問',
    vocabCount: '単語 {count}語',
    grammarCount: '文法 {count}項目',
    mockExamBannerTitle: '実戦模擬試験',
    mockExamBannerDesc: '本番同様の時間配分で解いて実力を測定しましょう。',
    startMockExam: '模試を始める',
    practiceTitle: '学習',
    practiceHeroTitle: '学習メニュー',
    practiceHeroSubtitle: '分野別トレーニングとスマートツールで効率的なTOPIK対策を。',
    byTypeSection: '分野別問題演習',
    readingPractice: '読解練習',
    readingPracticeDesc: 'TOPIK II 過去問読解（第102回・第83回全問収録）',
    listeningPractice: '聴解練習',
    listeningPracticeDesc: 'TOPIK II 過去問聴解（公式音声＆全問スクリプト）',
    writingPractice: '作文特訓',
    writingPracticeDesc: 'TOPIK II 作文対策（51〜54番 原稿用紙演習＆模範解答）',
    studyToolsSection: '学習ツール',
    smartWordbook: 'スマート単語帳',
    smartWordbookDesc: 'OneVoca 4大暗記モード（単語カード・クイズ・書き取り・自動再生）',
    grammarStudy: '文法学習',
    grammarStudyDesc: 'TOPIK必須文法パターンの検索＆例文確認',
    oneVocaTitle: 'OneVoca 4大暗記モード',
    oneVocaSubtitle: 'カード・クイズ・書き取り・自動再生で徹底暗記',
    flashcard: 'フラッシュカード',
    flashcardDesc: 'カードをめくって意味を確認',
    quiz: '選択式クイズ',
    quizDesc: '4択カスタムテスト',
    dictation: '書き取り練習',
    dictationDesc: '初声ヒントでスペルをマスター',
    autoplay: '自動再生',
    autoplayDesc: '移動中に耳で覚える単語プレーヤー',
    savedWords: '★ 保存した単語',
    addToVocabulary: '+ 単語帳に追加',
    savedToVocabulary: '単語帳に保存済み',
    searchVocabulary: '単語検索',
    flipCardHint: 'タップして意味を見る',
    memorized: '覚えた',
    needReview: 'もう一度',
    submitAnswer: '回答を提出',
    correctAnswer: '正解です！',
    wrongAnswer: '残念！正解：',
    studySourceSheetTitle: '学習する単語を選択',
    mySavedWordbook: 'マイ単語帳',
    mySavedWordbookDesc: '演習中に保存した自分だけの単語を集中学習',
    allTopikVocab: 'TOPIK必須単語 全体',
    allTopikVocabDesc: '試験頻出の重要単語を網羅して学習',
    wordsSavedCount: '{count}件 保存済み',
    searchGrammarHint: '文法を検索（例: -는데, -기 때문에）',
    examples: '例文',
    grammarDetail: '文法詳細',
    addToGrammar: '+ 文法帳に追加',
    savedToGrammar: '文法帳に保存済み',
    dailyWordChallenge: '今日の単語チャレンジ',
    dailyWordChallengeDesc: '毎日10単語でTOPIK語彙を完全マスター',
    startOneVoca: 'OneVoca 4大モードで学習',
    todayGrammar: '今日の文法',
    todayGrammarDesc: '1日1文法で韓国語の文構造をマスター',
    dailyStreak: '連続学習',
    streakDays: '{days}日連続',
    quickPractice: '実践練習へ',
    targetLevelLabel: '目標',
    wordsCount: '{count}単語',
    oneGrammarTitle: 'OneGrammar 文法学習',
    oneGrammarSubtitle: 'フラッシュカードと空欄補充クイズでTOPIK文法を攻略',
    grammarFlashcard: '文法フラッシュカード',
    grammarFlashcardDesc: 'パターン・接続規則・例文を確認',
    grammarQuiz: '文法空欄補充クイズ',
    grammarQuizDesc: '文脈に合った正しい文法を選択（TOPIK実戦形式）',
    grammarUsage: '接続規則',
    grammarCategoryAll: 'すべて',
    grammarCategoryReason: '理由・原因',
    grammarCategoryContrast: '対比・譲歩',
    grammarCategoryPurpose: '目的・意図',
    grammarCategoryCondition: '条件・仮定',
    grammarCategoryTime: '時間・順序',
    grammarCategoryOther: 'その他',
    quizScoreResult: '{total}問中 {correct}問正解！',
    nextQuestion: '次の問題',
    retryQuiz: 'もう一度解く',
    finishStudy: '学習完了',
    noGrammarForQuiz: 'クイズ用の文法データが不足しています。',
    dictTitle: '単語・文法 辞書',
    searchWordOrGrammar: '単語または文法を検索...',
    vocabSection: '語彙（単語）',
    grammarSection: '文法表現',
    dictNoResultsDesc: '辞書には未登録ですが、マイ単語帳に追加して後から復習できます。',
    dictTranslationLabel: '翻訳：',
    dictTranslating: '翻訳中...',
    viewNaverDict: 'Naver国語辞典で確認',
    mockExamTitle: '模擬試験',
    selectExamSession: '試験回次を選択',
    startExam: '試験を開始する',
    remainingTime: '残り時間',
    submitExam: '試験を提出する',
    confirmSubmitExam: '試験を提出して採点しますか？',
    examResult: '試験結果',
    totalScore: '総合スコア',
    viewExplanation: '解説を見る',
    questionNumberLabel: '問題 {number}番',
    dictionary: '辞書',
    viewScript: 'スクリプトを見る',
    charCount: '文字数',
    modelAnswer: '模範解答',
    bookmarkedQuestions: '保存した問題',
    bookmarkedVocab: 'マイ単語帳',
    bookmarkedGrammar: 'マイ文法帳',
    noBookmarks: '保存された項目はありません。',
    settingsTitle: '設定',
    appSettingsHeroTitle: 'アプリ設定',
    appSettingsHeroDesc: 'アカウント、学習環境、言語設定を一箇所で管理。',
    generalSettings: '一般設定',
    username: 'ユーザー名',
    email: 'メールアドレス',
    role: 'ロール',
    languageSetting: '言語設定',
    chooseLanguage: '言語選択 (Language)',
    languageChangedNotice: '言語を変更しました。',
    targetLevel: '目標級',
    fontSize: '文字サイズ',
    timezone: 'タイムゾーン',
    dataManagement: 'データ管理',
    clearBookmarks: 'ブックマーク初期化',
    clearBookmarksDesc: '保存したすべてのブックマークを削除',
    appInfo: 'アプリ情報',
    appInfoDesc: 'バージョン情報および利用規約',
    accountSection: 'アカウント',
    changePassword: 'パスワード変更',
    logout: 'ログアウト',
    adminMenu: '管理者メニュー',
    manageUsers: 'ユーザー管理',
    manageQuestionSets: '問題セット管理',
  );

  // -------------------------------------------------------------
  // French (Français)
  // -------------------------------------------------------------
  static const AppStrings _fr = AppStrings(
    locale: 'fr',
    navHome: 'Accueil',
    navPractice: 'Étude',
    navMockExam: 'Examen blanc',
    navSettings: 'Paramètres',
    confirm: 'Confirmer',
    cancel: 'Annuler',
    save: 'Enregistrer',
    delete: 'Supprimer',
    edit: 'Modifier',
    close: 'Fermer',
    back: 'Retour',
    next: 'Suivant',
    prev: 'Précédent',
    search: 'Rechercher',
    all: 'Tout',
    retry: 'Réessayer',
    loading: 'Chargement...',
    error: 'Une erreur est survenue',
    completed: 'Terminé',
    bookmark: 'Signet',
    bookmarked: 'Enregistré',
    listenPronunciation: 'Prononcer',
    round: 'Session',
    homeTitle: 'Accueil',
    homeGreeting: 'Bonjour, {name} !',
    homeSubtitle: 'Atteignons ensemble votre niveau cible de TOPIK aujourd’hui.',
    examSchedule: "Calendrier d'examen",
    noUpcomingExam: 'Aucun examen prévu prochainement.',
    daysLeft: 'J-{days}',
    quickStudy: 'Accès rapide',
    quickStudyDesc: 'Améliorez vos compétences par une pratique quotidienne.',
    bookmarksSummary: 'Signets',
    bookmarksSummaryDesc: 'Vos questions, vocabulaire et grammaire enregistrés.',
    questionsCount: '{count} questions',
    vocabCount: '{count} mots',
    grammarCount: '{count} grammaires',
    mockExamBannerTitle: 'Examen blanc réel',
    mockExamBannerDesc: 'Entraînez-vous dans les conditions réelles avec chronomètre.',
    startMockExam: "Commencer l'examen",
    practiceTitle: 'Entraînement',
    practiceHeroTitle: 'Entraînement',
    practiceHeroSubtitle: 'Préparation ciblée et outils intelligents pour réussir le TOPIK.',
    byTypeSection: 'Entraînement par section',
    readingPractice: 'Compréhension écrite',
    readingPracticeDesc: 'TOPIK II Lecture (Toutes questions des sessions 102 & 83)',
    listeningPractice: 'Compréhension orale',
    listeningPracticeDesc: 'TOPIK II Écoute (Audio authentique & transcriptions)',
    writingPractice: 'Expression écrite',
    writingPracticeDesc: 'TOPIK II Écriture (Q51~54 Papier manuscrit & corrigés)',
    studyToolsSection: "Outils d'étude",
    smartWordbook: 'Vocabulaire intelligent',
    smartWordbookDesc: '4 modes OneVoca (Cartes, Quiz, Dictée, Lecture auto)',
    grammarStudy: 'Grammaire',
    grammarStudyDesc: 'Recherche de points de grammaire et exemples',
    oneVocaTitle: '4 modes de mémorisation OneVoca',
    oneVocaSubtitle: 'Mémorisez avec Cartes, Quiz, Dictée et Lecture automatique',
    flashcard: 'Cartes mémoire',
    flashcardDesc: 'Retournez la carte pour voir le sens',
    quiz: 'Quiz QCM',
    quizDesc: 'Test personnalisé à 4 choix',
    dictation: 'Dictée',
    dictationDesc: "Entraînement à l'orthographe avec indices",
    autoplay: 'Lecture automatique',
    autoplayDesc: 'Lecteur audio pour écouter en déplacement',
    savedWords: '★ Mots enregistrés',
    addToVocabulary: '+ Ajouter au vocabulaire',
    savedToVocabulary: 'Enregistré dans le vocabulaire',
    searchVocabulary: 'Rechercher un mot',
    flipCardHint: 'Touchez pour retourner',
    memorized: 'Mémorisé',
    needReview: 'À revoir',
    submitAnswer: 'Valider',
    correctAnswer: 'Correct !',
    wrongAnswer: 'Incorrect ! Réponse : ',
    studySourceSheetTitle: 'Sélectionner les mots à étudier',
    mySavedWordbook: 'Mon vocabulaire enregistré',
    mySavedWordbookDesc: 'Révisez les mots sauvegardés durant vos exercices',
    allTopikVocab: 'Tout le vocabulaire TOPIK',
    allTopikVocabDesc: 'Apprentissage exhaustif du vocabulaire fréquent',
    wordsSavedCount: '{count} enregistrés',
    searchGrammarHint: 'Rechercher une grammaire (ex: -는데, -기 때문에)',
    examples: 'Exemples',
    grammarDetail: 'Détails de grammaire',
    addToGrammar: '+ Ajouter à la grammaire',
    savedToGrammar: 'Enregistré dans la grammaire',
    dailyWordChallenge: 'Défi de mots quotidiens',
    dailyWordChallengeDesc: 'Maîtrisez le vocabulaire TOPIK avec 10 mots par jour',
    startOneVoca: 'Étudier avec les 4 modes OneVoca',
    todayGrammar: 'Grammaire du jour',
    todayGrammarDesc: '1 structure grammaticale par jour',
    dailyStreak: 'Série quotidienne',
    streakDays: '{days} jours consécutifs',
    quickPractice: 'Pratique rapide',
    targetLevelLabel: 'Objectif',
    wordsCount: '{count} mots',
    oneGrammarTitle: 'Modes OneGrammar',
    oneGrammarSubtitle: 'Maîtrisez la grammaire TOPIK avec flashcards et quiz',
    grammarFlashcard: 'Flashcards de grammaire',
    grammarFlashcardDesc: 'Règles de conjugaison, motifs et exemples',
    grammarQuiz: 'Quiz de grammaire à trous',
    grammarQuizDesc: 'Remplissez les espaces vides avec la bonne grammaire',
    grammarUsage: 'Règles de conjugaison',
    grammarCategoryAll: 'Tous',
    grammarCategoryReason: 'Raison & Cause',
    grammarCategoryContrast: 'Contraste & Concession',
    grammarCategoryPurpose: 'But & Intention',
    grammarCategoryCondition: 'Condition & Hypothèse',
    grammarCategoryTime: 'Temps & Séquence',
    grammarCategoryOther: 'Autre',
    quizScoreResult: '{correct} / {total} corrects !',
    nextQuestion: 'Question suivante',
    retryQuiz: 'Recommencer',
    finishStudy: 'Terminer',
    noGrammarForQuiz: 'Pas assez de données pour le quiz.',
    dictTitle: 'Dictionnaire Mots & Grammaire',
    searchWordOrGrammar: 'Rechercher un mot ou une grammaire...',
    vocabSection: 'Vocabulaire (Mots)',
    grammarSection: 'Grammaire',
    dictNoResultsDesc: 'Non trouvé dans le dictionnaire, mais vous pouvez l’ajouter à votre liste.',
    dictTranslationLabel: 'Traduction : ',
    dictTranslating: 'Traduction en cours...',
    viewNaverDict: 'Consulter sur le dictionnaire Naver',
    mockExamTitle: 'Examen blanc',
    selectExamSession: 'Choisir la session',
    startExam: "Démarrer l'épreuve",
    remainingTime: 'Temps restant',
    submitExam: "Soumettre l'examen",
    confirmSubmitExam: "Voulez-vous vraiment terminer l'examen ?",
    examResult: "Résultats de l'examen",
    totalScore: 'Score total',
    viewExplanation: 'Voir les explications',
    questionNumberLabel: 'Question n°{number}',
    dictionary: 'Dictionnaire',
    viewScript: 'Voir la transcription',
    charCount: 'Nombre de caractères',
    modelAnswer: 'Modèle de réponse',
    bookmarkedQuestions: 'Questions enregistrées',
    bookmarkedVocab: 'Mon vocabulaire',
    bookmarkedGrammar: 'Ma grammaire',
    noBookmarks: 'Aucun élément enregistré.',
    settingsTitle: 'Paramètres',
    appSettingsHeroTitle: "Paramètres de l'application",
    appSettingsHeroDesc: 'Gérez votre compte, votre rythme d’étude et la langue.',
    generalSettings: 'Paramètres généraux',
    username: "Nom d'utilisateur",
    email: 'E-mail',
    role: 'Rôle',
    languageSetting: 'Langue',
    chooseLanguage: 'Choisir la langue (Language)',
    languageChangedNotice: 'Langue mise à jour.',
    targetLevel: 'Niveau visé',
    fontSize: 'Taille de police',
    timezone: 'Fuseau horaire',
    dataManagement: 'Gestion des données',
    clearBookmarks: 'Réinitialiser les signets',
    clearBookmarksDesc: 'Effacer tous les signets enregistrés',
    appInfo: "À propos de l'application",
    appInfoDesc: 'Informations de version et conditions',
    accountSection: 'Compte',
    changePassword: 'Changer le mot de passe',
    logout: 'Se déconnecter',
    adminMenu: 'Menu Administrateur',
    manageUsers: 'Gestion des utilisateurs',
    manageQuestionSets: 'Gestion des séries de questions',
  );

  // -------------------------------------------------------------
  // German (Deutsch)
  // -------------------------------------------------------------
  static const AppStrings _de = AppStrings(
    locale: 'de',
    navHome: 'Startseite',
    navPractice: 'Lernen',
    navMockExam: 'Probeprüfung',
    navSettings: 'Einstellungen',
    confirm: 'Bestätigen',
    cancel: 'Abbrechen',
    save: 'Speichern',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    close: 'Schließen',
    back: 'Zurück',
    next: 'Weiter',
    prev: 'Zurück',
    search: 'Suchen',
    all: 'Alle',
    retry: 'Wiederholen',
    loading: 'Wird geladen...',
    error: 'Ein Fehler ist aufgetreten',
    completed: 'Abgeschlossen',
    bookmark: 'Lesezeichen',
    bookmarked: 'Gespeichert',
    listenPronunciation: 'Aussprache hören',
    round: 'Runde',
    homeTitle: 'Startseite',
    homeGreeting: 'Hallo, {name}!',
    homeSubtitle: 'Lassen Sie uns heute gemeinsam Ihr TOPIK-Ziel erreichen.',
    examSchedule: 'Prüfungsplan',
    noUpcomingExam: 'Keine anstehende Prüfung geplant.',
    daysLeft: 'Noch {days} Tage',
    quickStudy: 'Schnellstart',
    quickStudyDesc: 'Bauen Sie Ihre Fähigkeiten durch tägliche Übung aus.',
    bookmarksSummary: 'Lesezeichen',
    bookmarksSummaryDesc: 'Ihre gespeicherten Fragen, Wörter und Grammatik.',
    questionsCount: '{count} Fragen',
    vocabCount: '{count} Wörter',
    grammarCount: '{count} Grammatik',
    mockExamBannerTitle: 'Echte Probeprüfung',
    mockExamBannerDesc: 'Üben Sie unter realen Prüfungsbedingungen mit Timer.',
    startMockExam: 'Prüfung starten',
    practiceTitle: 'Lernen',
    practiceHeroTitle: 'Lernbereich',
    practiceHeroSubtitle: 'Effektive TOPIK-Vorbereitung mit gezieltem Training.',
    byTypeSection: 'Training nach Bereichen',
    readingPractice: 'Leseverständnis',
    readingPracticeDesc: 'TOPIK II Lesen (Alle Fragen der 102. & 83. Runde)',
    listeningPractice: 'Hörverständnis',
    listeningPracticeDesc: 'TOPIK II Hören (Original-Audio & Transkriptionen)',
    writingPractice: 'Schreibtraining',
    writingPracticeDesc: 'TOPIK II Schreiben (Aufgaben 51~54 Manuskriptblatt & Musterlösungen)',
    studyToolsSection: 'Lernwerkzeuge',
    smartWordbook: 'Intelligentes Vokabelheft',
    smartWordbookDesc: 'OneVoca 4 Modi (Karteikarten, Quiz, Diktat, Autoplay)',
    grammarStudy: 'Grammatik',
    grammarStudyDesc: 'Wichtige Grammatikmuster suchen & Beispielsätze',
    oneVocaTitle: 'OneVoca 4 Lernmodi',
    oneVocaSubtitle: 'Wörter meistern mit Karten, Quiz, Diktat und Autoplay',
    flashcard: 'Karteikarten',
    flashcardDesc: 'Karte antippen und Bedeutung prüfen',
    quiz: 'Multiple-Choice-Quiz',
    quizDesc: 'Angepasster 4-Auswahl-Test',
    dictation: 'Diktat',
    dictationDesc: 'Rechtschreibtraining mit Konsonanten-Hinweisen',
    autoplay: 'Autoplay',
    autoplayDesc: 'Vokabeln unterwegs freihändig hören',
    savedWords: '★ Gespeicherte Wörter',
    addToVocabulary: '+ Zum Vokabelheft',
    savedToVocabulary: 'Im Vokabelheft gespeichert',
    searchVocabulary: 'Wort suchen',
    flipCardHint: 'Karte zum Umdrehen antippen',
    memorized: 'Gelernt',
    needReview: 'Nochmal wiederholen',
    submitAnswer: 'Antwort prüfen',
    correctAnswer: 'Richtig!',
    wrongAnswer: 'Leider falsch! Richtige Antwort: ',
    studySourceSheetTitle: 'Wortschatz zum Lernen auswählen',
    mySavedWordbook: 'Mein Vokabelheft',
    mySavedWordbookDesc: 'Wörter wiederholen, die beim Üben gespeichert wurden',
    allTopikVocab: 'Gesamter TOPIK-Kernwortschatz',
    allTopikVocabDesc: 'Umfassendes Lernen häufig geprüfter Vokabeln',
    wordsSavedCount: '{count} gespeichert',
    searchGrammarHint: 'Grammatik suchen (z.B. -는데, -기 때문에)',
    examples: 'Beispiele',
    grammarDetail: 'Grammatikdetails',
    addToGrammar: '+ Zur Grammatik hinzufügen',
    savedToGrammar: 'In Grammatik gespeichert',
    dailyWordChallenge: 'Tägliche Vokabel-Challenge',
    dailyWordChallengeDesc: 'Meistern Sie TOPIK-Vokabeln mit 10 Wörtern täglich',
    startOneVoca: 'Mit den 4 OneVoca-Modi lernen',
    todayGrammar: 'Grammatik des Tages',
    todayGrammarDesc: '1 Satzmuster pro Tag meistern',
    dailyStreak: 'Tägliche Serie',
    streakDays: '{days} Tage in Folge',
    quickPractice: 'Schnellübung',
    targetLevelLabel: 'Ziel',
    wordsCount: '{count} Wörter',
    oneGrammarTitle: 'OneGrammar Lernmodi',
    oneGrammarSubtitle: 'Meistern Sie TOPIK-Grammatik mit Karteikarten & Lückentext-Quiz',
    grammarFlashcard: 'Grammatik-Karteikarten',
    grammarFlashcardDesc: 'Muster, Konjugationsregeln und Beispielsätze',
    grammarQuiz: 'Grammatik-Lückentext',
    grammarQuizDesc: 'Wählen Sie die passende Grammatik für die Lücke aus',
    grammarUsage: 'Konjugationsregeln',
    grammarCategoryAll: 'Alle',
    grammarCategoryReason: 'Grund & Ursache',
    grammarCategoryContrast: 'Gegensatz & Einräumung',
    grammarCategoryPurpose: 'Zweck & Absicht',
    grammarCategoryCondition: 'Bedingung & Annahme',
    grammarCategoryTime: 'Zeit & Reihenfolge',
    grammarCategoryOther: 'Sonstige',
    quizScoreResult: '{correct} von {total} richtig!',
    nextQuestion: 'Nächste Frage',
    retryQuiz: 'Erneut versuchen',
    finishStudy: 'Beenden',
    noGrammarForQuiz: 'Nicht genügend Grammatikdaten für das Quiz.',
    dictTitle: 'Wörterbuch & Grammatik',
    searchWordOrGrammar: 'Wort oder Grammatik suchen...',
    vocabSection: 'Wortschatz (Vokabeln)',
    grammarSection: 'Grammatikformen',
    dictNoResultsDesc: 'Nicht im Verzeichnis, kann aber zum späteren Wiederholen gespeichert werden.',
    dictTranslationLabel: 'Übersetzung: ',
    dictTranslating: 'Wird übersetzt...',
    viewNaverDict: 'Im Naver-Wörterbuch ansehen',
    mockExamTitle: 'Probeprüfung',
    selectExamSession: 'Prüfungsrunde wählen',
    startExam: 'Prüfung beginnen',
    remainingTime: 'Verbleibende Zeit',
    submitExam: 'Prüfung abgeben',
    confirmSubmitExam: 'Möchten Sie die Prüfung wirklich abgeben?',
    examResult: 'Prüfungsergebnis',
    totalScore: 'Gesamtpunktzahl',
    viewExplanation: 'Erklärungen ansehen',
    questionNumberLabel: 'Frage {number}',
    dictionary: 'Wörterbuch',
    viewScript: 'Skript anzeigen',
    charCount: 'Zeichenanzahl',
    modelAnswer: 'Musterlösung',
    bookmarkedQuestions: 'Gespeicherte Fragen',
    bookmarkedVocab: 'Mein Vokabelheft',
    bookmarkedGrammar: 'Meine Grammatik',
    noBookmarks: 'Noch keine Elemente gespeichert.',
    settingsTitle: 'Einstellungen',
    appSettingsHeroTitle: 'App-Einstellungen',
    appSettingsHeroDesc: 'Verwalten Sie Konto, Lernumgebung und Sprache an einem Ort.',
    generalSettings: 'Allgemeine Einstellungen',
    username: 'Benutzername',
    email: 'E-Mail',
    role: 'Rolle',
    languageSetting: 'Sprache',
    chooseLanguage: 'Sprache auswählen (Language)',
    languageChangedNotice: 'Sprache geändert.',
    targetLevel: 'Zielstufe',
    fontSize: 'Schriftgröße',
    timezone: 'Zeitzone',
    dataManagement: 'Datenverwaltung',
    clearBookmarks: 'Lesezeichen zurücksetzen',
    clearBookmarksDesc: 'Alle gespeicherten Lesezeichen löschen',
    appInfo: 'App-Informationen',
    appInfoDesc: 'Versionshinweise & Richtlinien',
    accountSection: 'Konto',
    changePassword: 'Passwort ändern',
    logout: 'Abmelden',
    adminMenu: 'Admin-Menü',
    manageUsers: 'Benutzerverwaltung',
    manageQuestionSets: 'Fragesätze verwalten',
  );
}
